### ISSUE TITLE
MemberPage is broken

### ISSUE THREAD

**Issue by ondenman** [tmtmtmtm/kyrgyzstan-deputies#2]
`MemberPage` fails with:

```
NoMethodError: undefined method `tidy' for "":String
/.../kyrgyzstan-deputies/lib/member_page.rb:12:in `block in <class:MemberPage>'
```

**Comment by tmtmtmtm** [comment]
There is no `lib/member_page.rb` in `master`, so that looks like a problem with something you're developing locally?

Either way, that sort of problem is likely to be from an out-of-date version of `Scraped`, so I've bumped the Gemfile, and tidied up the problems resulting from that (new `rubocop` errors + CleanUrls decorator)
